version: '3.1'
services:
  web:
    build: .
    ports:
      - 4000:4000
    depends_on: 
      - postgres  
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "task"
    volumes: 
        - task-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4.7.7
    ports:
      - 8080:8080
volumes:
  task-db: